# Generated by Django 6.0 on 2025-12-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SALES_REP', 'Sales Representative')], default='SALES_REP', max_length=20),
        ),
    ]
